### ISSUE TITLE
Update Section headings

### ISSUE THREAD

**Issue by kreynoldsf5** [f5devcentral/f5-volterra-labs-101#43] opened 2021-03-08 14:10 UTC
```
Contents:

Pre-Work
Preparation
Site Spanning
Inventory Service
Recommendations Service
```

We need to be more descriptive here. This might require exposing 2 layers in this TOC since each section is quite busy.

**Comment by codygreen** [comment] 2021-03-08 21:37
duplicate of #59

**Closed by codygreen** 2021-03-08 21:37 UTC
